
const  ActionTypes = {
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAILS:'REGISTER_FAILS',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILS:"LOGIN_FAILS"
};
export  default  ActionTypes;

