
const  ActionTypes = {
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAILS:'REGISTER_FAILS',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILS:"LOGIN_FAILS",
    GET_ORDERS_SUCCESS:'GET_ORDERS_SUCCESS',
    GET_ORDERS_FAIL:'GET_ORDERS_FAIL',
    NO_ORDERS_FOR_USER:'NO_ORDERS_FOR_USER'

};
export  default  ActionTypes;

